### ISSUE TITLE
Redux devtools support

### ISSUE THREAD

**Issue by kubk** [kubk/mobx-log#1]
Is it needed? Put :+1:  if you think so :)

**Comment by akkayy** [comment]
Would be great to have redux devtools support, esp when the official [Mobx devtools](https://github.com/mobxjs/mobx-devtools) & [Redux-remote](https://github.com/zalmoxisus/mobx-remotedev/issues) both are unmaintained :-( 

No point in reviving mobx devtools, as redux devtools is a better option as it could cover both redux & mobx..

**Comment by kubk** [comment]
Hi @akkayy . What do you need the most from mobx-remotedev? Personally I've stopped to use remotedev because mobx-log covers all my needs. It logs store changes, you can have an access to store in browser console using store._STORE_NAME_ . So you can see observables, computeds and call actions

**Comment by akkayy** [comment]
Thanks for the quick response @kubk. Love your logger, will definitely use it as a supplement. Really sad that mobx that's such a smart one, has really no stable devtools. 

Where devtools shine is when we use both mutable and immutable data in our state.. In large applications, we can end up with immutable nested objects of many levels like this: 

![image](https://user-images.githubusercontent.com/73772701/144421178-e9e57ff0-f8c6-469b-817e-e22af7144f92.png)

This sort of data as computed, gets harder to track during dev on the console.

**Comment by kubk** [comment]
Hi @TechAkayy 
The Redux devtools support has been added in 1.0.0

**Comment by TechAkayy** [comment]
Wow, this is fantastic. Thanks bunch, will test it out.

**Comment by TechAkayy** [comment]
Thanks @kubk. Just started using v1.0.0 and it's great to see computed in the console. And thanks bunch for redux-devtools support, on that topic, I have added a related feature request here - https://github.com/kubk/mobx-log/issues/34
