### ISSUE TITLE
Feature Request: Log filter

### ISSUE THREAD

**Issue by akkayy** [kubk/mobx-log#16]
Would be great to extend api to log only certain info.

**Comment by akkayy** [comment]
Actually, I could just use console filter instead "mobx [c]"... to show only the computed props ;-)

**Comment by kubk** [comment]
@akkayy Yes, that was the idea. If you need to log something - just use Chrome built-in filters, they are powerful. Adding a filter to library is also possible. Would it solve your issue if I add filters like `{ computed: true, actions: false, observables: false }`?

**Comment by akkayy** [comment]
Yes, that's simple yet powerful, thanks bunch!

**Comment by kubk** [comment]
Published as mobx-log@0.8.3

**Comment by kubk** [comment]
<img width="455" alt="Screen Shot 2021-12-02 at 21 46 38" src="https://user-images.githubusercontent.com/22447849/144484018-628f7042-26cd-47a7-9416-96950fe7dda5.png">

Added all the info to README
