### ISSUE TITLE
configureMakeLoggable readme update

### ISSUE THREAD

**Issue by akkayy** [kubk/mobx-log#20]
Readme requires update. `observables: false` instead of `observable: false`

```
import { configureMakeLoggable } from 'mobx-log';

configureMakeLoggable({
  filters: {
    computeds: true,
    actions: true,
    observable: false, // change to "observables: false"
  }
});
```

**Comment by kubk** [comment]
@akkayy Thank you for noticing. Would you like to make a PR? It should be enough to click Pencil icon on the README file and commit directly using GitHub interface.
