### ISSUE TITLE
Get error "using mobx-log without an initializer function is deprecated"

### ISSUE THREAD

**Issue by inoyakaigor** [kubk/mobx-log#35]
I get the error "using mobx-log without an initializer function is deprecated" when I do as the README says

Repro [MOBX-LOG-TEST-CASE.ZIP](https://github.com/kubk/mobx-log/files/9468259/MOBX-LOG-TEST-CASE.ZIP)

Entrypoint (client.tsx). Pay attention to order of call `configureDevtools()` and import an App component:
```javascript
import {render} from 'react-dom'
import {configureDevtools} from 'mobx-log'
configureDevtools()

import {configure} from 'mobx'

import {App} from './App'

configure({
    enforceActions: 'always'
})

render(
    <App />,
    document.getElementById('root')
)
```
which imports an app (App.tsx):
```javascript
import React from 'react'
import {formsStore} from './stores/forms'

export const App = () => {
    console.log(formsStore)
    return <div>MY FOCKING OSOME APP</div>
}
```
which imports a store (stores/forms.ts):
```javascript
import {makeAutoObservable} from 'mobx'
import {makeLoggable} from 'mobx-log'

class FormsStore {
    common: Record<string, any> = {}

    constructor() {
        makeAutoObservable(this)
        makeLoggable(this)
    }

    setValue = (key, value) => this.common[key] = value
}

const formsStore = new FormsStore

export {formsStore}
```

I found out webpack changed import order and I think thats why error caused
<img width="874" alt="image" src="https://user-images.githubusercontent.com/1235286/187874654-02610c3e-6ce7-4806-9c97-697f2eb5f54e.png">

**Comment by kubk** [comment]
Thanks for reporting it. Despite the fact that it is a fault of singletons, it makes sense to not force people rewriting their app because of devtools. From now on `mobx-log` detects Redux devtools automatically. If one wants to use browser logger despite of Redux devtools presence, he should turn them off.

**Comment by kubk** [comment]
Since it's a BC break please bump your mobx-log

I usually do it with `npm i mobx-log@latest`
