### ISSUE TITLE
Feature request - show computeds in the browser

### ISSUE THREAD

**Issue by mnieber** [kubk/mobx-log#36]
I'm using `applyFormatters` to have a better formatting of mobx containers (in Chrome), but I noticed that `get properties` are no longer shown when I do this. Is it possible to still shows these somehow? E.g. have the "three dots" for get properties that expand to the actual value when you click on it, or any other solution that comes to mind.

**Comment by kubk** [comment]
Thanks for the idea. The support of computeds have been added in 2.1.1
