### ISSUE TITLE
MST support

### ISSUE THREAD

**Issue by AaronPorts** [kubk/mobx-log#37]
Can I use it with mobx-state-tree?

**Comment by kubk** [comment]
Hi @AaronPorts 

I haven't worked with MST. Since MST is built on top of Mobx you may try using mobx-log with MST. By the way MST has its own middlewares for loggin: https://github.com/mobxjs/mobx-state-tree/tree/master/packages/mst-middlewares/src

**Comment by kubk** [comment]
Closed for inactivity
