### ISSUE TITLE
Set making first letter in store name to lowercase optional

### ISSUE THREAD

**Issue by inoyakaigor** [kubk/mobx-log#41]
Today I learned mobx-log provide object with all stores into global scope. It's a cool feature but for case when name starts from acronums it is look not great:
![image](https://github.com/kubk/mobx-log/assets/1235286/7135d7d9-269b-44a5-a4f5-3ff29dda5443)
Maybe it's better to make this feature optional?

**Comment by kubk** [comment]
It is already optional: https://github.com/kubk/mobx-log#access-stores-as-global-variables-in-browser-console

**Comment by inoyakaigor** [comment]
@kubk I mena optional lowercase

**Comment by kubk** [comment]
@inoyakaigor Ok, I'll just remove the code that lowers the case

**Comment by kubk** [comment]
Thank you, published as mobx-log@2.2.0
