### ISSUE TITLE
Enable logging for data structures

### ISSUE THREAD

**Issue by agentodessa** [kubk/mobx-log#9]
Please add an ability to see logging for Map, Set, WeakMap, WeakSet. I suppose those things are missed in implementation. 

Thanks

**Comment by kubk** [comment]
@agentodessa Thank you for the request. I've added support for Map & Set. Screenshots attached here: https://github.com/kubk/mobx-log/pull/10

Please update to the latest version

**Comment by kubk** [comment]
Does Mobx support WeakMap & WeakSet? 

![image](https://user-images.githubusercontent.com/22447849/136000092-8703ea88-6212-4156-bfbc-381332d38e6a.png)
